# Generated by Django 2.2.6 on 2019-12-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_data_user_user_analysis_list_user_project_list'),
    ]

    operations = [
    ]
