# Generated by Django 2.2.6 on 2019-12-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191202_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_analysis_list',
            name='cnv_software',
            field=models.CharField(default='CNVnator', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_analysis_list',
            name='data_table',
            field=models.CharField(default='./', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_analysis_list',
            name='reference',
            field=models.CharField(default='hg38', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_analysis_list',
            name='sv_software',
            field=models.CharField(default='Delly', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_analysis_list',
            name='variant_software',
            field=models.CharField(default='GAKT', max_length=128),
            preserve_default=False,
        ),
    ]
