# Generated by Django 2.2.6 on 2019-12-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191202_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='adapter',
            field=models.CharField(default='Truseq', max_length=128),
            preserve_default=False,
        ),
    ]
