# Generated by Django 2.2 on 2019-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_data_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_analysis_list',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
