# Generated by Django 2.2 on 2019-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_user_analysis_list_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_analysis_list',
            name='email_send',
            field=models.CharField(default='邮件还送', max_length=128),
            preserve_default=False,
        ),
    ]
