# Generated by Django 2.2 on 2020-01-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qc',
        ),
    ]
